on: [push]

stages:
  stage:
    name: Build Docker
    displayName: Creating Docker Environnment
      runs-on: ubuntu-18.04
      name: CI/CD Automation
      step:
      - uses: actions/checkout@v2
      - name: Create Docker
        uses: ./.github/
        id: 'Dockerfile'
  
