on: [push]

stages:
  stage:
    name: Build Docker
    runs-on: ubuntu-18.04
      step:
      - uses: actions/checkout@v2
      - name: Create Docker
        uses: ./.github/
          id: 'Dockerfile'
  
