on:
  push:
    branches:
#    - master (Commented out for testing)
#  release:
#    types:
#    - createder

jobs:
  build:
    #strategy:
    #  matrix:
    #    os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest #${{ matrix.os }} To reduce test time
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm i install --global vsce
    - run: npm i install --global typescript
    - run: npm i install --global mocha 
    #- run: npm i install --global ts-mocha   
    #- run: npm i install --global gulp
    #- run: ts-mocha ./src/test/runTest.ts
    #  if: runner.os == 'Linux'
    - run: npm test
    #  if: runner.os != 'Linux'
