#Several lines are commented out. This workflow will test on MACOS, Windows, and Linux
#But while I am still figuring out actions and CD/CD I've cut some things out to save on run time
on:
  push:
    branches:
#    - master (Commented out for testing)
#  release:
#    types:
#    - createder

jobs:
  build:
    #strategy:
    #  matrix:
    #    os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest #${{ matrix.os }} To reduce test time
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Install Node.js
    #  uses: actions/setup-node@v1
    #  with:
    #    node-version: 10.x
    - run: npm ci
    #  if: runner.os == 'Linux'
    - run: npm test
    #  if: runner.os != 'Linux'
