on: [push]

jobs:
  -stage: Build Docker
    displayName: Building the Docker
    runs-on: ubuntu-18.04
    - uses: actions/checkout@v2
    - name: Create Docker
      uses: ./.github/
        id: 'Dockerfile'
  
